### PR TITLE
Bringing 4.12 changes into theories subtree.

### PR DESCRIPTION
**Pull request by pholser**
Should satisfy #20.

### CODE REVIEW

**Comment by marcphilipp** [comment]
@dsaff I don't have commit privileges for junit-contrib. Can you take a look?

**Comment by dsaff** [comment]
Will do, but likely not until Tuesday, sorry.

**Comment by marcphilipp** [comment]
@dsaff This is a friendly reminder. :smile:

**Comment by dsaff** [comment]
Thanks, Paul!

**Comment by pholser** [comment]
@dsaff @marcphilipp Thanks to you! Happy to help.

**Pull request merged**
